qcacld: fix build error in function 'ol_check_fw_hash'
Patch fixes the build error on platforms where "CONFIG_CNSS" is not
defined:
CORE/SERVICES/BMI/ol_fw.c:364:5: error: unused variable 'digest'
[-Werror=unused-variable]

Change-Id: I0eed31e8497f538685e398d62673e8e5a9d9c83b
CRs-Fixed: 707238